Repository 16-SulGore/Algorithm, pull requests merged in 2021-12, with the labels that each got.

#5 1259
  1259.py
  test.txt.txt
Labels: 하

#6 1436: 영화감독 숌
  1436.py
Labels: 하

#7 파일 정리
  class2/1259.py
  class2/1436.py
Labels: chore

#4 Class4/#1
  README.md
  class4/15652.py
Labels: 백트래킹

#8 Class4/#1
  class4/15652.py
  class4/15657.py
  class4/15666.py
Labels: DFS, 하, 백트래킹

#10 Class4/#1
  Class4/N_M12.py
  Class4/N_M4.py
  Class4/N_M8.py
  README.md
Labels: DFS, 하, 백트래킹

#11 Class4/#1
  class4/N_15652.py
  class4/N_15657.py
  class4/N_15666.py
Labels: DFS, 하, 백트래킹

#9 1주차 - class 2
  class2/1654.py
  class2/1874.py
  class2/1920.py
  class2/1929.py
Labels: 하, 이분탐색, 스택

#15 Class4 시간초과 문제들
  Class4/bag.py
  Class4/binary_search.py
  Class4/fibonacci6.py
Labels: fail, Dp, 중, 상, 이분탐색, 트리
