Repository 16-SulGore/Algorithm, pull requests merged in 2022-06, with the labels that each got.

#75 [CJW] 징검다리 건너기
  kakao_kt/src/main/kotlin/0506_징검다리건너기.kt
Labels: 이분탐색, 카카오, Level3, Kotlin

#74 [CJW] 길찾기 게임
  kakao_kt/src/main/kotlin/0506_길찾기게임.kt
Labels: Tree, 카카오, Level3, Kotlin

#73 [CJW] 기둥과 보 설치
  kakao_kt/src/main/kotlin/0505_기둥과보설치.kt
Labels: 카카오, Level3, Kotlin

#70 [CJW] 경주로 건설
  kakao_kt/src/main/kotlin/0421_후보키.kt
  kakao_kt/src/main/kotlin/0503_경주로건설.kt
  kakao_kt/src/test/kotlin/CandidateKeyTest.kt
Labels: 카카오, Level3, Kotlin

#67 [KJH] 경주로 건설
  programmers/build_road.py
Labels: BFS, 카카오, Level3, Python

#69 [KJH] 기둥과 보 설치
  programmers/column_row.py
Labels: 카카오, Level3, Python

#83 [CJW] 랜선자르기
  .gitignore
  naver/week01/1654_랜선자르기.py
Labels: 하, 이분탐색, Python

#88 [CJW] 나무자르기
  naver/week01/2805_나무자르기.py
Labels: 이분탐색

#94 [CJW] 가장 긴 증가하는 부분 수열2
  naver/week01/12015_LIS2.py
Labels: Dp, 중, 이분탐색, Python

#97 [CJW] 가장 긴 증가하는 부분수열 5
  naver/week01/14003_LIS5.py
Labels: Dp, 중, 이분탐색

#93 [CJW] 세 용액
  naver/week01/2473_세용액.py
Labels: 하, Python, Two Pointer

#82 [BDH] 랜선 자르기
  naver_01/1654_랜선자르기.py
Labels: 이분탐색

#85 [BDH] 세 용액
  naver_01/2473_세용액.py
Labels: Two Pointer

#92 [CJW] 용액
  naver/week01/2467_용액.py
Labels: 하, Two Pointer

#100 [HJS] 텀 프로젝트
  termProject.js
Labels: DFS, JavaScript

#96 [HJS] 용액
  solutionWater.js
Labels: JavaScript, Two Pointer

#95 [HJS] 내려가기
  README.md
  archive/kakao.md
  goDown.js
  goDown.py
Labels: Dp, JavaScript, Python
