Repository 16-SulGore/Algorithm, pull requests merged in 2022-05, with the labels that each got.

#61 [BDH] 2문제 해결
  week_03/불량사용자.js
  week_03/불량사용자.py
  week_03/합승택시요금.js
Labels: Dp, 백트래킹, 카카오, Level3, JavaScript

#62 [PSH] 자물쇠와 열쇠
  week_3/자물쇠와 열쇠.js
  week_3/자물쇠와 열쇠.py
Labels: Graph, 카카오, Level3, JavaScript

#63 [PSH] 표 편집
  week_3/표 편집.js
  week_3/표 편집.py
Labels: 카카오, Level3, JavaScript

#64 [PSH] 보석
  week_3/보석 쇼핑 시간초과.py
  week_3/보석 쇼핑.js
  week_3/보석 쇼핑.py
Labels: 구현, 카카오, Level3, JavaScript

#76 [PSH] 경주로 건설
  week_4/경주로 건설 시간초과.py
  week_4/경주로 건설.js
  week_4/경주로 건설.py
Labels: Dp, BFS, 카카오, Level3, JavaScript, Python

#77 [PSH] 광고 삽입
  week_4/광고 삽입.js
  week_4/광고 삽입.py
Labels: 카카오, Level3, JavaScript, Python
