Repository 16-SulGore/Algorithm, pull requests merged in 2022-04, with the labels that each got.

#30 [BDH]괄호 변환
  week_01/괄호변환.py
Labels: 구현, 카카오, Level2

#29 [BDH]오픈 채팅방
  week_01/오픈채팅방.py
Labels: 구현, 카카오, Level2

#28 [CJW]오픈채팅방
  kakao/0411_오픈채팅방.py
Labels: 카카오, Level2

#34 [KJH] 오픈채팅방
  programmers/jacquard.py
  programmers/open_chat.py
Labels: 카카오, Level2

#35 fail: 메뉴 리뉴얼
  kakao/0413_메뉴리뉴얼.py
Labels: fail, 상, 카카오, Level2

#38 [CJW] 괄호변환
  kakao/0414_괄호변환.py
Labels: 구현, 카카오, Level2

#40 [CJW] 3문제 해결
  kakao/0416_거리두기확인하기.py
  kakao/0416_뉴스클러스터링.py
  kakao/0416_수식최대화.py
Labels: 카카오, Level2

#31 [BDH]뉴스 클러스터링
  week_01/뉴스클러스터링.py
Labels: 구현, 카카오, Level2

#33 [BDH]거리두기 확인하기
  week_01/거리두기확인하기.py
Labels: BFS, 카카오, Level2

#36 [BDH]메뉴 리뉴얼
  week_01/메뉴리뉴얼 시간초과.py
  week_01/메뉴리뉴얼 접근 실패.py
  week_01/메뉴리뉴얼.py
Labels: 구현, 상, 카카오, Level2

#45 [BDH] 수식최대화
  week_01/수식최대화.py
Labels: 구현, 카카오, Level2

#32 [PSH] 오픈채팅방
  week_1/오픈채팅방.py
Labels: 카카오, Level2

#42 [PSH] 메뉴 리뉴얼
  week_1/메뉴리뉴얼.py
Labels: 구현, 카카오, Level2

#43 [PSH] 괄호 변환
  week_1/괄호변환.py
Labels: 구현, 카카오, Level2

#44 [PSH] #27 3문제 해결
  week_1/거리두기 확인하기.py
  week_1/뉴스 클러스터링.py
  week_1/수식 최대화.py
Labels: 카카오, Level2

#49 [BDH] 튜플
  week_01/튜플.py
Labels: 카카오, Level2

#46 [CJW] 튜플튜플튜플튜플
  kakao/0417_튜플.py
  kakao/0417_튜플_refactor.py
  kakao/0417_튜플_short.py
Labels: 카카오, Level2

#54 [CJW] 코틀린 세팅
  .gitignore
  kakao_kt/build.gradle.kts
  kakao_kt/gradle.properties
  kakao_kt/gradlew
  kakao_kt/gradlew.bat
  kakao_kt/local.properties
  kakao_kt/settings.gradle.kts
  kakao_kt/src/main/kotlin/main.kt
Labels: chore

#56 [CJW] 후보키 (kt)
  kakao_kt/src/main/kotlin/0421_후보키.kt
  kakao_kt/src/test/kotlin/CandidateKeyTest.kt
Labels: 백트래킹, 카카오, Level2, Kotlin

#50 [BDH]후보키
  week_02/후보키.py
Labels: 카카오, Level2

#52 [BDH] 2문제 해결
  week_02/캐시.py
  week_02/프렌즈4블록.py
Labels: 구현, 카카오, Level2

#51 [PSH] 후보키
  week_2/후보키.py
Labels: 구현, 카카오, Level2

#57 [PSH] 프렌즈 4블록
  week_2/프렌즈4블록.py
Labels: 카카오, Level2

#60 [PSH] 캐시
  week_2/캐시.js
  week_2/캐시.py
Labels: 구현, 카카오, Level2, JavaScript

#53 [KJH] 후보키
  programmers/candidate_key.py
Labels: 카카오, Level2
